# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Mina Nabil Sami - Blog
email: mina.nsami@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://minasami.com" # the base hostname & protocol for your site, e.g. http://example.com

# seo
social:
  name: Mina Nabil Sami
  links:
    - https://twitter.com/MinaNabilSami
    - https://www.linkedin.com/in/mnsami
    - https://github.com/mnsami
    - https://instagram/minansami
twitter:
  username: MinaNabilSami
  card: summary

author:
  name: "Mina Nabil Sami"
  twitter: MinaNabilSami

show_excerpts: true

# Build settings
# theme: plainwhite

include: ['_pages', 'htaccess']
markdown: kramdown
exclude_from_localization: ["images", "css"]
parallel_localization: true

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
  - Makefile

# website param
params:
  name: Mina Nabil Sami
  tagline: Developer. Chef. Gamer.
  date_format: "%b %-d, %Y"
  sitemap: true

  navigation:
    - title: About Me
      url: "/about"

  social_links:
    twitter: MinaNabilSami
    github: mnsami
    linkedIn: in/mnsami # format: locale/username
    instagram: minansami

collections:
  site_tags:
    output: true
    permalink: tags/:path/
