# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Mina Nabil Sami - Blog
email: mina.nsami@gmail.com
description: "Senior software engineer with 16+ years building scalable backend systems. Expert in PHP (Symfony, Laravel), Node.js, AWS, and DevOps. Technical blog, mentorship, and consulting."
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://minasami.com" # the base hostname & protocol for your site, e.g. http://example.com

# seo
defaults:
  - scope:
      path: ""
    values:
      image: "/assets/portfolio.png"
  - scope:
      path: "_posts"
      type: "posts"
    values:
      layout: "post"
      author: "Mina Nabil Sami"
      image: "/assets/portfolio.png"

social:
  name: Mina Nabil Sami
  links:
    - https://twitter.com/MinaNabilSami
    - https://www.linkedin.com/in/mnsami
    - https://github.com/mnsami
    - https://instagram.com/minansami

twitter:
  username: MinaNabilSami
  card: summary_large_image

author:
  name: "Mina Nabil Sami"
  twitter: MinaNabilSami

logo: "/assets/portfolio.png"
google_site_verification: "4_ae8nciHvt4z5mqfgMMrtRRAK9XnXbOzZ8W6Z5nAhY"
show_excerpts: true

# Jekyll Feed Plugin
feed:
  posts_limit: 20
  excerpt_only: false

include: ['_pages', '.htaccess']
markdown: kramdown

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
  - Makefile
  - .github/

# website param
params:
  name: Mina Nabil Sami
  tagline: Developer. Chef. Gamer.
  date_format: "%b %-d, %Y"
  sitemap: true
  analytics_id: "G-0HJ1QG88ND"

  navigation:
    - title: About Me
      url: "/about"

  social_links:
    twitter: MinaNabilSami
    github: mnsami
    linkedIn: in/mnsami # format: locale/username
    instagram: minansami
